### ISSUE TITLE
Mark automatically forward ported PRs in the list of PR for a given IB

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmssdt-ib#9]
In the old IB page, PRs that are automatically forward ported (e.g. 9_4_X -> 9_4_MAOD_X) are marked with a double arrow symbol in front in the old IB page, and this helps in identifying how they entered into the build. I think that this feature is missing in the new page, it might be helpful to keep it.

**Comment by gudrutis** [comment]
Implemented.
If, however, you do not see the changes, clean browser cache and restart the browser.
